/**
 * Start-Stop RTC for 4 relays adapter
 */

#include <Wire.h>

#include "config.h" // Dynamically generated by the compile Task during the build process
#include "rtcTimer.h"
#include "wifiAccessPoint.h"
#include "httpServer.h"

///** Start the Serial interface */
void setupSerial() {
    Serial.begin(BAUD_RATE);
    while (!Serial);
    Serial.println();
}

/** Start the I2C interface */
void setupI2C() {
    Serial.println("Start the I2C interface");
	Wire.begin();
}

/** Setup the device */
void setup() {
    setupSerial();
    setupSstRelays();
    setupI2C();
    setupTimer();
    setupAccessPoint();
    setupHttpServer();
}

/** The main execution loop */
void loop() {
    // Handle the HTTP client requests
    serverHandleClient();

    // Check if there is an RTC alarm occured
    checkTimerAlarm(updateSstRelays);

    delay(10);
}
