#include <ESP8266WiFi.h>
#include "config.h" // Dynamically generated by the compile Task during the build process

// WiFi Access point credentials
const char *ssid = APSSID;
const char *password = APPSK;

/** Setup the Wifi Access Point */
void setupAccessPoint() {
    Serial.println("Configuring access point...");
    /* You can remove the password parameter if you want the AP to be open. */
    WiFi.softAP(ssid, password);

    IPAddress myIP = WiFi.softAPIP();
    Serial.print("AP IP address: ");
    Serial.println(myIP);
}
